#ifndef VL_COMMON_SHADING_MODEL_GLSL
#define VL_COMMON_SHADING_MODEL_GLSL

const uint SHADING_MODEL_DEFAULT_LIT = 0u;
const uint SHADING_MODEL_UNLIT = 1u;
const uint SHADING_MODEL_SUBSURFACE = 2u;
const uint SHADING_MODEL_PREINTEGRATED_SKIN = 3u;
const uint SHADING_MODEL_CLEAR_COAT = 4u;
const uint SHADING_MODEL_SUBSURFACE_PROFILE = 5u;
const uint SHADING_MODEL_TWOSIDED_FOLIAGE = 6u;
const uint SHADING_MODEL_HAIR = 7u;
const uint SHADING_MODEL_CLOTH = 8u;
const uint SHADING_MODEL_EYE = 9u;

#endif
