#pragma once

#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include "material/generator/materialParameterIncludeGenerator.h"

namespace VL
{

// Immutable source batch prepared from one stable M_*.json monitor event.
// Generated bytes stay in memory until the enclosing world/runtime transaction
// has completed every fallible prepare step.
struct MaterialDefinitionReloadBatch
{
    uint64_t batchId = 0;
    std::vector<std::string> changedSources;
    std::vector<MaterialParameterIncludeGenerator::GeneratedIncludeCandidate>
        generatedIncludes;
    std::map<std::string, std::string> includeOverlays;
    std::map<std::string, std::string> sourceDigests;
};

} // namespace VL
